server:
  port: 6001
spring:
  application:
    name: gateway-server
  profiles:
    active: nacos,envs,gateway
  cloud:
    gateway:
      # 全局的跨域处理
      globalcors:
        # 解决options请求被拦截问题
        add-to-simple-url-handler-mapping: true
        # 允许哪些网站的跨域请求
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8090"
            # 允许的跨域ajax的请求方式
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            # 允许在请求中携带的头信息
            allowedHeaders: "*"
            # 是否允许携带cookie
            allowCredentials: true
            # 这次跨域检测的有效期
            maxAge: 360000
      discovery:
        locator:
          enable: true