spring:
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: ${platform.nacos.server-addr}
        namespace: ${platform.nacos.namespace}
        group: ${platform.nacos.group}