spring:
  redis:
    host: 10.1.1.16
    port: 6379
    timeout: 3000
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.37.5.66:8848
  session:
    store-type: redis
mybatis-plus:
  typeEnumsPackage: com.cy.platform.cloud.gateway.core.constant