spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.37.5.66:8848
  session:
    store-type: redis
mybatis-plus:
  typeEnumsPackage: com.cy.platform.cloud.gateway.constant